services:
  minio:
    image: minio/minio
    container_name: Verdict360-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: https://localhost:9000
      MINIO_BROWSER_REDIRECT_URL: https://localhost:9001
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
      - ./docker/minio/certs:/root/.minio/certs
    command: server /data --console-address ":9001" --certs-dir /root/.minio/certs
    healthcheck:
      test: ['CMD', 'curl', '-k', '-f', 'https://localhost:9000/minio/health/live']
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  minio_data:
