name: Deploy

on:
  push:
    branches: [main]
    tags:
      - 'v*'

jobs:
  build-and-push-web:
    name: Build and Push Web
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push Web image
        uses: docker/build-push-action@v4
        with:
          context: ./web
          push: true
          tags: verdict360/web:latest,verdict360/web:${{ github.sha }}
      
      - name: Build and push API image
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: verdict360/api:latest,verdict360/api:${{ github.sha }}
  
  deploy:
    name: Deploy to Environment
    needs: build-and-push-web
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /opt/verdict360
            docker-compose pull
            docker-compose up -d
            docker system prune -af
          EOF
